name: Security Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scans:
    name: ${{ matrix.job-name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - job-name: Semgrep SAST
            tool: semgrep
            artifact-name: semgrep-results
            output-file: semgrep.sarif
          - job-name: Trivy SCA
            tool: trivy-sca
            artifact-name: trivy-sca-results
            output-file: trivy-sca.sarif
          - job-name: Trivy Dockerfile Check
            tool: trivy-dockerfiles
            artifact-name: trivy-dockerfiles-results
            output-file: trivy-dockerfiles.sarif

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Semgrep SAST scan
        if: matrix.tool == 'semgrep'
        run: |
            pip install semgrep
            semgrep --config p/default --sarif --output semgrep.sarif . || true

      - name: Run Trivy SCA
        if: matrix.tool == 'trivy-sca'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: ${{ matrix.output-file }}
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Run Trivy Dockerfile Check
        if: matrix.tool == 'trivy-dockerfiles'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          format: 'sarif'
          output: ${{ matrix.output-file }}
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}-${{ github.ref_name }}-${{ github.sha }}
          path: ${{ matrix.output-file }}
